In [10]:
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import PolynomialFeatures

In [12]:
feature=np.array([[-100,100],
                  [-200,200],
                  [500,-500],
                  [600,-600],
                  [9000,-9000]
    
    
    
])

feature2=np.array([[1,2],
                   [2,3],
                   [1,1]
    
    
])


X:= (X-mean)/(Sigma)

In [9]:
standardiser_object=preprocessing.StandardScaler()

standardised_feature=standardiser_object.fit_transform(feature)
print(standardised_feature)



[[-0.58287986  0.58287986]
 [-0.611175    0.611175  ]
 [-0.41310902  0.41310902]
 [-0.38481389  0.38481389]
 [ 1.99197776 -1.99197776]]


Polynomial and Interaction features

In [19]:
# x1,x2,x1^2,x1x2,x2^2
polynomial_interaction= PolynomialFeatures(degree=2,include_bias=False)
#include_bais=True gives a column of 1 for bias/ theta0

new_features=polynomial_interaction.fit_transform(feature2)

print(new_features)

[[1. 2. 1. 2. 4.]
 [2. 3. 4. 6. 9.]
 [1. 1. 1. 1. 1.]]


#TO READ - DETECTING OUTLIARS, GROUPING OBSERVATIONS