In [24]:
import numpy as np
from scipy import sparse


In [6]:
matrix=np.array([[1,2,4],
                 [0,4,2],
                 [0,0,1]
    
    
])


<h4>Sparse Matrix</h4>
stores only non zero elements 

In [15]:
matrix_sparse=sparse.csc_matrix(matrix)


row_indices, col_indices = matrix_sparse.indices, matrix_sparse.indptr
nonzero_values = matrix_sparse.data



<h4> Flattening a matrix

In [18]:
print(matrix.flatten())

[1 2 4 0 4 2 0 0 1]


Matrix Operations

In [31]:
#rank
print(np.linalg.matrix_rank(matrix))


#determinant
print(np.linalg.det(matrix))

#trace
print(matrix.trace())

#eigenvalues and eigenvectors

eigenvalues,eigenvectors=np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)


#inverting
print((np.linalg.inv(matrix)))
      


3
4.0
6
[1. 4. 1.]
[[ 1.00000000e+00  5.54700196e-01 -1.00000000e+00]
 [ 0.00000000e+00  8.32050294e-01 -5.55111512e-17]
 [ 0.00000000e+00  0.00000000e+00  8.32667268e-17]]
[[ 1.   -0.5  -3.  ]
 [ 0.    0.25 -0.5 ]
 [ 0.    0.    1.  ]]
